### ISSUE TITLE
Crashes when trying to update to Phaser 3.60.0

### ISSUE THREAD

**Issue by gabeklavans** [pawap90/phaser3-ts-snowpack-eslint#1]
I tried to update to Phaser 3.60, but I can't load any games. I get this error:

```
Unhandled Runtime Error
SyntaxError: ambiguous indirect export: default
```

And the lines throwing this in the source code are as such:
```
import Phaser from "../_snowpack/pkg/phaser.v3.60.0.js";
```

I haven't gotten around to testing this on a fresh Snowpack project, but I thought I'd bring it up here, since I am seeing this across multiple of my devices using this template.

**Comment by pawap90** [comment]
@gabeklavans I hope it's not too late. I just updated all packages to their latest versions, including Phaser to v3.60.0.

I was able to reproduce the error you mentioned here and fixed it by replacing default imports to other alternatives:

```ts
import * as Phaser from 'phaser';
// instead of 
import Phaser from 'phaser';
```

Or if I needed more specific imports:

```ts
import { Scene, Types } from 'phaser';

export class InitialScene extends Scene {
    //...
}
```

For what I've seen the error was probably related to the [new ESM support](https://github.com/photonstorm/phaser/blob/v3.60.0/changelog/3.60/ESMSupport.md) added to Phaser 3.60.0, but I'm not certain.

Anyway, you can see all the changes I had to make to update everything and make it work in this PR: #2

**Comment by gabeklavans** [comment]
Awesome, thanks so much. I'll be upgrading my apps with this info 😀
